---
title: "Cabingan_K-means"
author: "Stephanie Cabingan"
date: "2026-06-07"
output: html_document
---

```{r}
# install.packages("factoextra")
library(factoextra)
```

Read csv file
```{r}
df <- read.csv("morphology_data.csv")
```

Exclude Sex Column
```{r}
clmph_data <- df[,-2]
clmph_data
```

Cleaning the data
```{r}
good <- complete.cases(clmph_data)
head(clmph_data[good, ])
morpho_data <- clmph_data[good, ]
```

Standardization
```{r}
morpho_scaled <- scale(morpho_data[-1])
```

Kmeans
```{r}
kmeans_morpho <- kmeans(morpho_scaled, centers = 3, nstart = 25)
```

View Cluster Assignments
```{r}
head(kmeans_morpho$cluster)
```

Summary of results
```{r}
kmeans_morpho
```

Scatterplot
```{r}
SVL <- morpho_scaled[,1]
TD <- morpho_scaled[,2]
plot(
  SVL, TD,
  col = kmeans_morpho$cluster,
  pch = 19,
  xlab = "SVL (scaled)",
  ylab = "TD (scaled)",
  main = "Morphology K-means Clustering"
)

points(kmeans_morpho$centers, col = 1:3, pch = 8, cex = 2, lwd = 2)
```

Kmeans Loop
```{r}
ss <- numeric(10)
                 
for(k in 1:10){
  kmeans(morpho_scaled, centers = k, nstart = 25)
  ss[k] <- kmeans_morpho$tot.withinss
}
```

Elbow Curve
```{r}
fviz_nbclust(
  morpho_scaled,
  kmeans,
  method = "wss",
  k.max = 10
)
```

Kmeans cluster w/ Optimal K
```{r}
kml <- kmeans(morpho_scaled, centers = 2, nstart = 10)
```

View cluster assignments
```{r}
head(kml$cluster)
```

Summary of results
```{r}
kml
```

Scatterplot with K = 2
```{r}
SVL_2 <- morpho_scaled[,1]
TD_2 <- morpho_scaled[,2]
plot(
  SVL_2, TD_2,
  col = kml$cluster,
  pch = 19,
  xlab = "SVL (scaled)",
  ylab = "TD (scaled)",
  main = "Morphology K-means (Loop) Clustering"
)

points(kmeans_morpho$centers, col = 1:2, pch = 19, cex = 2, lwd = 2)
```